### ISSUE TITLE
Problemas ao rodar npm run build e npm run start

### ISSUE THREAD

**Issue by renanmoraes** [talesluna/base-nodejs-api-es6#10]
Bom estou tendo problemas ao rodar a API em produção.

```0|easyImmo | SyntaxError: Unexpected token import
0|easyImmo |     at createScript (vm.js:80:10)
0|easyImmo |     at Object.runInThisContext (vm.js:152:10)
0|easyImmo |     at Module._compile (module.js:624:28)
0|easyImmo |     at Object.Module._extensions..js (module.js:671:10)
0|easyImmo |     at Module.load (module.js:573:32)
0|easyImmo |     at tryModuleLoad (module.js:513:12)
0|easyImmo |     at Function.Module._load (module.js:505:3)
0|easyImmo |     at Object.<anonymous> (/home/renan/.nvm/versions/node/v9.3.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
0|easyImmo |     at Module._compile (module.js:660:30)
0|easyImmo |     at Object.Module._extensions..js (module.js:671:10)
PM2        | App [easyImmobile 1.0] with id [0] and pid [6165], exited with code [1] via signal [SIGINT]
PM2        | Script /home/renan/projects/ei-api-data/dist/app.js had too many unstable restarts (16). Stopped. "errored"
```

Este é o erro que está aparecendo quando rodo

`pm2 log`

O que pode ser  e como concertar ?

**Comment by talesluna** [comment]
tem como mandar mais desse log? apenas com este trecho não consegui encontrar muita coisa

**Comment by talesluna** [comment]
problemas relativos a configuração pessoal.
